name: test-and-build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B clean verify
      - name: Upload Reports
        shell: bash
        with:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          export PROJECT_NAME="code-challenges-java"
          export COVERAGE_FILE="jacoco-report/target/site/jacoco-aggregate/jacoco.xml"
          export CODACY_PROJECT_NAME="$PROJECT_NAME"
          # export CODACY_PROJECT_TOKEN="$CODACY_TOKEN"

          # Submit Coverage Data to Codacy
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r $COVERAGE_FILE
      - name: Update dependency graph for Dependabot Alerts
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
